// products.js - Ühishanke Mega Shop Products
module.exports = [
  { id: 1, name: "Amaizin Coco Crispy Rolls Original 6x140g", price: 4.99, stock: 25, image: "", description: "Delicious coconut rolls", soldCount: 0 },
  { id: 2, name: "Amaizin Organic Crispy Chili Oil 6x170g", price: 6.49, stock: 18, image: "", description: "Spicy crispy chili oil", soldCount: 0 },
  { id: 3, name: "Amaizin Tomato Corn Rolls 14x100g", price: 5.99, stock: 30, image: "", description: "Tomato flavored corn rolls", soldCount: 0 },
  { id: 4, name: "Organic Almond Butter 250g", price: 8.99, stock: 15, image: "", description: "Smooth almond butter", soldCount: 0 },
  { id: 5, name: "Organic Peanut Butter 250g", price: 6.99, stock: 20, image: "", description: "Creamy peanut butter", soldCount: 0 },
  { id: 6, name: "Organic Cashew Butter 250g", price: 9.49, stock: 12, image: "", description: "Rich cashew butter", soldCount: 0 },
  { id: 7, name: "Organic Chia Seeds 200g", price: 4.29, stock: 40, image: "", description: "High in omega-3", soldCount: 0 },
  { id: 8, name: "Organic Flax Seeds 200g", price: 3.99, stock: 35, image: "", description: "Nutty and nutritious", soldCount: 0 },
  { id: 9, name: "Organic Oatmeal 500g", price: 3.49, stock: 50, image: "", description: "Whole grain oats", soldCount: 0 },
  { id: 10, name: "Organic Quinoa 500g", price: 5.49, stock: 22, image: "", description: "High protein grain", soldCount: 0 },
  { id: 11, name: "Organic Brown Rice 1kg", price: 4.79, stock: 30, image: "", description: "Nutty brown rice", soldCount: 0 },
  { id: 12, name: "Organic Red Lentils 500g", price: 3.99, stock: 28, image: "", description: "Rich in protein", soldCount: 0 },
  { id: 13, name: "Organic Green Lentils 500g", price: 4.19, stock: 25, image: "", description: "Healthy lentils", soldCount: 0 },
  { id: 14, name: "Organic Chickpeas 500g", price: 4.29, stock: 27, image: "", description: "Protein-packed legumes", soldCount: 0 },
  { id: 15, name: "Organic Black Beans 500g", price: 4.49, stock: 20, image: "", description: "Versatile beans", soldCount: 0 },
  { id: 16, name: "Organic Red Kidney Beans 500g", price: 4.59, stock: 22, image: "", description: "Rich in fiber", soldCount: 0 },
  { id: 17, name: "Organic Lentil Pasta 250g", price: 3.99, stock: 18, image: "", description: "High protein pasta", soldCount: 0 },
  { id: 18, name: "Organic Chickpea Pasta 250g", price: 4.19, stock: 16, image: "", description: "Gluten-free pasta", soldCount: 0 },
  { id: 19, name: "Organic Coconut Flour 500g", price: 5.49, stock: 14, image: "", description: "Gluten-free flour", soldCount: 0 },
  { id: 20, name: "Organic Almond Flour 500g", price: 6.49, stock: 12, image: "", description: "Perfect for baking", soldCount: 0 },
  { id: 21, name: "Organic Oat Flour 500g", price: 4.49, stock: 25, image: "", description: "Soft and nutritious", soldCount: 0 },
  { id: 22, name: "Organic Brown Sugar 500g", price: 3.79, stock: 30, image: "", description: "Naturally sweet", soldCount: 0 },
  { id: 23, name: "Organic Coconut Sugar 500g", price: 4.19, stock: 28, image: "", description: "Low GI sugar", soldCount: 0 },
  { id: 24, name: "Organic Maple Syrup 250ml", price: 7.99, stock: 15, image: "", description: "Rich maple flavor", soldCount: 0 },
  { id: 25, name: "Organic Agave Syrup 250ml", price: 6.99, stock: 18, image: "", description: "Sweet syrup alternative", soldCount: 0 },
  { id: 26, name: "Organic Apple Juice 1L", price: 3.49, stock: 22, image: "", description: "100% pure juice", soldCount: 0 },
  { id: 27, name: "Organic Orange Juice 1L", price: 3.79, stock: 20, image: "", description: "Fresh and sweet", soldCount: 0 },
  { id: 28, name: "Organic Coconut Water 500ml", price: 2.99, stock: 25, image: "", description: "Natural hydration", soldCount: 0 },
  { id: 29, name: "Organic Almond Milk 1L", price: 3.99, stock: 18, image: "", description: "Dairy-free milk", soldCount: 0 },
  { id: 30, name: "Organic Soy Milk 1L", price: 3.79, stock: 20, image: "", description: "Vegan alternative", soldCount: 0 },
  { id: 31, name: "Organic Cashew Milk 1L", price: 4.29, stock: 16, image: "", description: "Creamy and smooth", soldCount: 0 },
  { id: 32, name: "Organic Hazelnut Spread 250g", price: 5.99, stock: 14, image: "", description: "Chocolate hazelnut delight", soldCount: 0 },
  { id: 33, name: "Organic Cocoa Powder 250g", price: 4.49, stock: 20, image: "", description: "Rich dark cocoa", soldCount: 0 },
  { id: 34, name: "Organic Dark Chocolate 70% 100g", price: 3.99, stock: 25, image: "", description: "Bitter-sweet chocolate", soldCount: 0 },
  { id: 35, name: "Organic Dark Chocolate 85% 100g", price: 4.49, stock: 18, image: "", description: "Extra dark chocolate", soldCount: 0 },
  { id: 36, name: "Organic Coconut Chips 100g", price: 2.99, stock: 30, image: "", description: "Crunchy coconut snack", soldCount: 0 },
  { id: 37, name: "Organic Trail Mix 150g", price: 3.99, stock: 22, image: "", description: "Nuts and dried fruits", soldCount: 0 },
  { id: 38, name: "Organic Sunflower Seeds 200g", price: 2.49, stock: 25, image: "", description: "Healthy snack", soldCount: 0 },
  { id: 39, name: "Organic Pumpkin Seeds 200g", price: 3.49, stock: 20, image: "", description: "Rich in protein", soldCount: 0 },
  { id: 40, name: "Organic Sesame Seeds 200g", price: 2.99, stock: 18, image: "", description: "High calcium content", soldCount: 0 },
  { id: 41, name: "Organic Mixed Nuts 200g", price: 5.49, stock: 15, image: "", description: "Nutty variety", soldCount: 0 },
  { id: 42, name: "Organic Raisins 200g", price: 2.99, stock: 25, image: "", description: "Sweet dried grapes", soldCount: 0 },
  { id: 43, name: "Organic Cranberries 200g", price: 3.29, stock: 20, image: "", description: "Tart dried cranberries", soldCount: 0 },
  { id: 44, name: "Organic Blueberries 200g", price: 3.99, stock: 18, image: "", description: "Antioxidant-rich", soldCount: 0 },
  { id: 45, name: "Organic Strawberries 200g", price: 3.99, stock: 22, image: "", description: "Sweet & juicy", soldCount: 0 },
  { id: 46, name: "Organic Bananas 1kg", price: 2.49, stock: 40, image: "", description: "Fresh bananas", soldCount: 0 },
  { id: 47, name: "Organic Apples 1kg", price: 3.49, stock: 35, image: "", description: "Crunchy apples", soldCount: 0 },
  { id: 48, name: "Organic Pears 1kg", price: 3.29, stock: 30, image: "", description: "Sweet pears", soldCount: 0 },
  { id: 49, name: "Organic Grapes 500g", price: 4.49, stock: 28, image: "", description: "Seedless grapes", soldCount: 0 },
  { id: 50, name: "Organic Kiwi 500g", price: 4.99, stock: 22, image: "", description: "Fresh kiwi fruit", soldCount: 0 }
];