// products.js - Ühishanke Ultimate Example Products

const products = [
  { id: 1, name: "Product 1", price: 12.99, stock: 15, lastChecked: null, image: "add-image-1.png", soldCount: 0, favedCount: 0 },
  { id: 2, name: "Product 2", price: 8.5, stock: 30, lastChecked: null, image: "add-image-2.png", soldCount: 0, favedCount: 0 },
  { id: 3, name: "Product 3", price: 20.0, stock: 10, lastChecked: null, image: "add-image-3.png", soldCount: 0, favedCount: 0 },
  { id: 4, name: "Product 4", price: 15.25, stock: 5, lastChecked: null, image: "add-image-4.png", soldCount: 0, favedCount: 0 },
  { id: 5, name: "Product 5", price: 7.75, stock: 12, lastChecked: null, image: "add-image-5.png", soldCount: 0, favedCount: 0 },
  { id: 6, name: "Product 6", price: 11.5, stock: 20, lastChecked: null, image: "add-image-6.png", soldCount: 0, favedCount: 0 },
  { id: 7, name: "Product 7", price: 9.99, stock: 8, lastChecked: null, image: "add-image-7.png", soldCount: 0, favedCount: 0 },
  { id: 8, name: "Product 8", price: 14.2, stock: 25, lastChecked: null, image: "add-image-8.png", soldCount: 0, favedCount: 0 },
  { id: 9, name: "Product 9", price: 6.5, stock: 18, lastChecked: null, image: "add-image-9.png", soldCount: 0, favedCount: 0 },
  { id: 10, name: "Product 10", price: 19.99, stock: 6, lastChecked: null, image: "add-image-10.png", soldCount: 0, favedCount: 0 },
  { id: 11, name: "Product 11", price: 13.5, stock: 14, lastChecked: null, image: "add-image-11.png", soldCount: 0, favedCount: 0 },
  { id: 12, name: "Product 12", price: 21.0, stock: 11, lastChecked: null, image: "add-image-12.png", soldCount: 0, favedCount: 0 },
  { id: 13, name: "Product 13", price: 10.75, stock: 17, lastChecked: null, image: "add-image-13.png", soldCount: 0, favedCount: 0 },
  { id: 14, name: "Product 14", price: 18.0, stock: 9, lastChecked: null, image: "add-image-14.png", soldCount: 0, favedCount: 0 },
  { id: 15, name: "Product 15", price: 16.25, stock: 20, lastChecked: null, image: "add-image-15.png", soldCount: 0, favedCount: 0 },
  { id: 16, name: "Product 16", price: 5.99, stock: 22, lastChecked: null, image: "add-image-16.png", soldCount: 0, favedCount: 0 },
  { id: 17, name: "Product 17", price: 9.5, stock: 19, lastChecked: null, image: "add-image-17.png", soldCount: 0, favedCount: 0 },
  { id: 18, name: "Product 18", price: 12.0, stock: 15, lastChecked: null, image: "add-image-18.png", soldCount: 0, favedCount: 0 },
  { id: 19, name: "Product 19", price: 14.5, stock: 13, lastChecked: null, image: "add-image-19.png", soldCount: 0, favedCount: 0 },
  { id: 20, name: "Product 20", price: 7.25, stock: 18, lastChecked: null, image: "add-image-20.png", soldCount: 0, favedCount: 0 },
  { id: 21, name: "Product 21", price: 15.0, stock: 9, lastChecked: null, image: "add-image-21.png", soldCount: 0, favedCount: 0 },
  { id: 22, name: "Product 22", price: 11.25, stock: 20, lastChecked: null, image: "add-image-22.png", soldCount: 0, favedCount: 0 },
  { id: 23, name: "Product 23", price: 19.0, stock: 7, lastChecked: null, image: "add-image-23.png", soldCount: 0, favedCount: 0 },
  { id: 24, name: "Product 24", price: 13.75, stock: 15, lastChecked: null, image: "add-image-24.png", soldCount: 0, favedCount: 0 },
  { id: 25, name: "Product 25", price: 8.99, stock: 21, lastChecked: null, image: "add-image-25.png", soldCount: 0, favedCount: 0 },
  { id: 26, name: "Product 26", price: 17.5, stock: 12, lastChecked: null, image: "add-image-26.png", soldCount: 0, favedCount: 0 },
  { id: 27, name: "Product 27", price: 6.75, stock: 25, lastChecked: null, image: "add-image-27.png", soldCount: 0, favedCount: 0 },
  { id: 28, name: "Product 28", price: 14.0, stock: 10, lastChecked: null, image: "add-image-28.png", soldCount: 0, favedCount: 0 },
  { id: 29, name: "Product 29", price: 9.25, stock: 16, lastChecked: null, image: "add-image-29.png", soldCount: 0, favedCount: 0 },
  { id: 30, name: "Product 30", price: 20.0, stock: 8, lastChecked: null, image: "add-image-30.png", soldCount: 0, favedCount: 0 },
  { id: 31, name: "Product 31", price: 12.5, stock: 14, lastChecked: null, image: "add-image-31.png", soldCount: 0, favedCount: 0 },
  { id: 32, name: "Product 32", price: 10.0, stock: 19, lastChecked: null, image: "add-image-32.png", soldCount: 0, favedCount: 0 },
  { id: 33, name: "Product 33", price: 18.5, stock: 7, lastChecked: null, image: "add-image-33.png", soldCount: 0, favedCount: 0 },
  { id: 34, name: "Product 34", price: 9.99, stock: 23, lastChecked: null, image: "add-image-34.png", soldCount: 0, favedCount: 0 },
  { id: 35, name: "Product 35", price: 13.5, stock: 12, lastChecked: null, image: "add-image-35.png", soldCount: 0, favedCount: 0 },
  { id: 36, name: "Product 36", price: 16.25, stock: 10, lastChecked: null, image: "add-image-36.png", soldCount: 0, favedCount: 0 },
  { id: 37, name: "Product 37", price: 7.5, stock: 18, lastChecked: null, image: "add-image-37.png", soldCount: 0, favedCount: 0 },
  { id: 38, name: "Product 38", price: 11.0, stock: 15, lastChecked: null, image: "add-image-38.png", soldCount: 0, favedCount: 0 },
  { id: 39, name: "Product 39", price: 14.75, stock: 9, lastChecked: null, image: "add-image-39.png", soldCount: 0, favedCount: 0 },
  { id: 40, name: "Product 40", price: 19.99, stock: 6, lastChecked: null, image: "add-image-40.png", soldCount: 0, favedCount: 0 },
  { id: 41, name: "Product 41", price: 8.25, stock: 17, lastChecked: null, image: "add-image-41.png", soldCount: 0, favedCount: 0 },
  { id: 42, name: "Product 42", price: 13.0, stock: 14, lastChecked: null, image: "add-image-42.png", soldCount: 0, favedCount: 0 },
  { id: 43, name: "Product 43", price: 10.5, stock: 20, lastChecked: null, image: "add-image-43.png", soldCount: 0, favedCount: 0 },
  { id: 44, name: "Product 44", price: 15.25, stock: 8, lastChecked: null, image: "add-image-44.png", soldCount: 0, favedCount: 0 },
  { id: 45, name: "Product 45", price: 12.0, stock: 12, lastChecked: null, image: "add-image-45.png", soldCount: 0, favedCount: 0 },
  { id: 46, name: "Product 46", price: 16.5, stock: 11, lastChecked: null, image: "add-image-46.png", soldCount: 0, favedCount: 0 },
  { id: 47, name: "Product 47", price: 9.0, stock: 19, lastChecked: null, image: "add-image-47.png", soldCount: 0, favedCount: 0 },
  { id: 48, name: "Product 48", price: 14.5, stock: 13, lastChecked: null, image: "add-image-48.png", soldCount: 0, favedCount: 0 },
  { id: 49, name: "Product 49", price: 7.75, stock: 22, lastChecked: null, image: "add-image-49.png", soldCount: 0, favedCount: 0 },
  { id: 50, name: "Product 50", price: 20.0, stock: 10, lastChecked: null, image: "add-image-50.png", soldCount: 0, favedCount: 0 }
];

module.exports = products;